### PR TITLE
Fix uninitialized variable errors when building with gcc-11

### LINKED ISSUE #3364: Uninitialized variable error when compiling with gcc 11
**Describe the bug**
QMCPACK doesn't compile correctly with gcc-11 

**To Reproduce**
1. `develop`
2. `cmake -GNinja -D CMAKE_C_COMPILER=gcc -D CMAKE_CXX_COMPILER=g++ -D QMC_MPI=0 ../qmcpack`
3. `ninja`

**Expected behavior**
gcc-11 compilation must work

**System:**
Ubuntu 20.10 with default gcc-11 docker container image from [here](https://hub.docker.com/layers/ubuntu/library/ubuntu/impish-20210722/images/sha256-993294f9f183ba17a61857e31f589ddcda0e8f9636fc12d8fd34922f24539c36?context=explore) on Ubuntu 20.04 host.

**Additional context**
Error related to initialization:
```
$ ninja
[4/77] Building CXX object src/Numerics/tests/CMakeFiles/test_numerics.dir/test_grid_functor.cpp.o
FAILED: src/Numerics/tests/CMakeFiles/test_numerics.dir/test_grid_functor.cpp.o 
/usr/bin/g++ -DADD_ -DCATCH_CONFIG_ENABLE_BENCHMARKING -DH5_USE_16_API -DHAVE_CONFIG_H -DHAVE_LIBBOOST -DHAVE_LIBHDF5 -DOPENMP_NO_COMPLEX -DUSE_REAL_STRUCT_FACTOR -Drestrict=__restrict__ -I/home/user/qmcpack/src -Isrc -I/home/user/qmcpack/external_codes/boost_multi -I/home/user/qmcpack/external_codes/catch -I/home/user/qmcpack/src/Utilities -I/home/user/qmcpack/src/Containers -I/home/user/qmcpack/src/Platforms -I/home/user/qmcpack/src/io -isystem /usr/include/hdf5/serial -isystem /usr/include/libxml2 -Werror -fopenmp -finline-limit=1000 -fstrict-aliasing -funroll-all-loops -Wno-deprecated -Wvla -Wcomment -Wmisleading-indentation -Wmaybe-uninitialized -Wuninitialized -Wreorder -Wno-unknown-pragmas -Wno-sign-compare -Wsuggest-override -ffast-math -march=native -O3 -DNDEBUG -std=c++17 -MD -MT src/Numerics/tests/CMakeFiles/test_numerics.dir/test_grid_functor.cpp.o -MF src/Numerics/tests/CMakeFiles/test_numerics.dir/test_grid_functor.cpp.o.d -o src/Numerics/tests/CMakeFiles/test_numerics.dir/test_grid_functor.cpp.o -c /home/user/qmcpack/src/Numerics/tests/test_grid_functor.cpp
/home/user/qmcpack/src/Numerics/tests/test_grid_functor.cpp: In function 'void qmcplusplus::____C_A_T_C_H____T_E_S_T____0()':
/home/user/qmcpack/src/Numerics/tests/test_grid_functor.cpp:30:22: error: 'grid.qmcplusplus::LinearGrid<double, qmcplusplus::Vector<double, std::allocator<double> > >::<unnamed>.qmcplusplus::OneDimGridBase<double, qmcplusplus::Vector<double, std::allocator<double> > >::lower_bound' may be used uninitialized [-Werror=maybe-uninitialized]
   30 |   LinearGrid<double> grid;
      |                      ^~~~
/home/user/qmcpack/src/Numerics/tests/test_grid_functor.cpp:30:22: error: 'grid.qmcplusplus::LinearGrid<double, qmcplusplus::Vector<double, std::allocator<double> > >::<unnamed>.qmcplusplus::OneDimGridBase<double, qmcplusplus::Vector<double, std::allocator<double> > >::upper_bound' may be used uninitialized [-Werror=maybe-uninitialized]
/home/user/qmcpack/src/Numerics/tests/test_grid_functor.cpp:30:22: error: 'grid.qmcplusplus::LinearGrid<double, qmcplusplus::Vector<double, std::allocator<double> > >::<unnamed>.qmcplusplus::OneDimGridBase<double, qmcplusplus::Vector<double, std::allocator<double> > >::Delta' may be used uninitialized [-Werror=maybe-uninitialized]
/home/user/qmcpack/src/Numerics/tests/test_grid_functor.cpp:30:22: error: 'grid.qmcplusplus::LinearGrid<double>::<anonymous>.qmcplusplus::OneDimGridBase<double, qmcplusplus::Vector<double, std::allocator<double> > >::DeltaInv' may be used uninitialized [-Werror=maybe-uninitialized]
In file included from /home/user/qmcpack/src/Numerics/tests/test_grid_functor.cpp:15:
/home/user/qmcpack/src/Numerics/OneDimGridBase.h:35:8: error: 'grid.qmcplusplus::LinearGrid<double>::<anonymous>.qmcplusplus::OneDimGridBase<double, qmcplusplus::Vector<double, std::allocator<double> > >::GridTag' may be used uninitialized [-Werror=maybe-uninitialized]
   35 | struct OneDimGridBase
      |        ^~~~~~~~~~~~~~
/home/user/qmcpack/src/Numerics/tests/test_grid_functor.cpp:30:22: note: 'grid.qmcplusplus::LinearGrid<double>::<anonymous>.qmcplusplus::OneDimGridBase<double, qmcplusplus::Vector<double, std::allocator<double> > >::GridTag' was declared here
   30 |   LinearGrid<double> grid;
      |                      ^~~~
cc1plus: all warnings being treated as errors
[21/77] Building CXX object src/QMCWaveFunctions/tests/CMakeFiles/test_wavefunction_trialwf.dir/test_TrialWaveFunction_diamondC_2x1x1.cpp.o
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Adding initialization in variables due to an error when building with gcc-11.
Fixes #3364 

## What type(s) of changes does this code introduce?

- Bugfix

### Does this introduce a breaking change?

- Yes

## What systems has this change been tested on?
Ubuntu 20.10 + gcc-11 docker image on Ubuntu 20.04 host

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

File: src/Numerics/OneDimGridBase.h [hunk 1]
```diff
@@ -38,13 +38,13 @@ struct OneDimGridBase
   typedef CT Array_t;
 
 
-  int GridTag;
-  int num_points;
-  value_type lower_bound;
-  value_type upper_bound;
+  int GridTag            = 0;
+  int num_points         = 0;
```
Comment (ye-luo) [inline src/Numerics/OneDimGridBase.h:42]: Specified already in the constructor.
I feel better to consistently use the constructor.
T is always a float pointer number, so just use 0 if it is the intended value.

Comment (williamfgc) [reply src/Numerics/OneDimGridBase.h]: Good catch.

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
Start testing in-house

**Comment by prckent** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]
