### PR TITLE
Increase epsilon for complex and mixed precision test on ROCm

### LINKED ISSUE #3601: deterministic-unit_test_estimators test failing with ROCm, Complex, Mixed precision breaking CI
**Describe the bug**
`deterministic-unit_test_estimators` test fails on nitrogen CI using complex and mixed precision build
Error is epsilon related:

```
qmcpack/src/Estimators/tests/test_MomentumDistribution.cpp:192: FAILED:
  CHECK( data[id] == Approx(ref_data[id]) )
with expansion:
  0.08944f == Approx( 0.089425981 )
```

**To Reproduce**

1. `develop`
2. ``cmake -GNinja -DCMAKE_C_COMPILER=/opt/rocm/llvm/bin/clang -DCMAKE_CXX_COMPILER=/opt/rocm/llvm/bin/clang++ -DQMC_MPI=0 -DENABLE_CUDA=ON -DQMC_CUDA2HIP=ON -DCMAKE_PREFIX_PATH=/opt/OpenBLAS/0.3.18 -DQMC_COMPLEX=1 -DQMC_MIXED_PRECISION=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo .. `
3. `ninja`
4. `ctest -VV -R deterministic-unit_test_estimators`

**Expected behavior**
Test must pass

**System:**
 - nitrogen

**Additional context**
Test was recently added. Will do a PR.

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Current CI is failing on nitrogen for complex and mixed precision tests
This PR just bumps epsilon in floating point comparison
Tests were recently added in #3592 
Failure seen in #3599 
Fixes #3601 

## What type(s) of changes does this code introduce?

- Bugfix

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
nitrogen

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by williamfgc** [comment]
Start testing in-house

File: src/Estimators/tests/test_MomentumDistribution.cpp [hunk 1]
```diff
@@ -189,7 +189,13 @@ TEST_CASE("MomentumDistribution::accumulate", "[estimators]")
   //std::cout<<"}\n\n\n";
 
   for (size_t id = 0; id < ref_data.size(); ++id)
-    CHECK(data[id] == Approx(ref_data[id]));
+  {
+     #ifdef MIXED_PRECISION
+     CHECK(data[id] == Approx(ref_data[id]).epsilon(0.00002));
+     #else
+     CHECK(data[id] == Approx(ref_data[id]));
```
Comment (prckent) [inline src/Estimators/tests/test_MomentumDistribution.cpp:196]: Can you explicitly put the default numerical comparison/epsilon for the full precisision case (currently line 196) to make it clear what the difference in the comparison is?

**Comment by williamfgc** [comment]
Start testing in-house

**Review by prckent — APPROVED** [review]
LGTM subject to CI

**Review by ye-luo — APPROVED** [review]
