### PR TITLE
Fix &vec[0] assertion failure when size 0

### LINKED ISSUE #5630: Fatal bug / assertion failure in PooledData
**Describe the bug**

Mixed precision debug builds on CPU result in >100 test failures due to an assertion failure in PooledData.cpp . Full precision debug builds with the same setup are OK.

```
test_new_drivers_mpi: qmcpack/src/Containers/Pools/PooledData.cpp:62: void PooledData<T>::add(std::complex<_Up>*, std::complex<_Up>*) [with T1 = float; T = double]: Assertion `t_n > 0' failed.
test_new_drivers_mpi: qmcpack/src/Containers/Pools/PooledData.cpp:62: void PooledData<T>::add(std::complex<_Up>*, std::complex<_Up>*) [with T1 = float; T = double]: Assertion `t_n > 0' failed.
```
```
$ grep "det.*Failed" ctest.out |head -20
 258/2195 Test   #43: deterministic-unit_test_new_drivers_mpi-r2 ..................................................................***Failed    0.75 sec
 753/2195 Test   #39: deterministic-unit_test_estimators_mpi ......................................................................***Failed    0.43 sec
 757/2195 Test   #44: deterministic-unit_test_new_drivers_mpi-r3 ..................................................................***Failed    0.55 sec
 944/2195 Test #1622: deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers_sdj-r2-t2 ........................................***Failed  Required regular expression not found. Regex=[QMCPACK execution completed successfully
 946/2195 Test #1623: deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers_sdj-r2-t2-kinetic ................................***Failed    0.03 sec
 947/2195 Test #1624: deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers_sdj-r2-t2-totenergy ..............................***Failed    0.03 sec
 948/2195 Test #1625: deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers_sdj-r2-t2-eeenergy ...............................***Failed    0.03 sec
 949/2195 Test #1649: deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers_sdbatch_sdj-r2-t2 ................................***Failed  Required regular expression not found. Regex=[QMCPACK execution completed successfully
 950/2195 Test #1626: deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers_sdj-r2-t2-samples ................................***Failed    0.05 sec
 951/2195 Test #1627: deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers_sdj-r2-t2-potential ..............................***Failed    0.04 sec
 952/2195 Test #1628: deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers_sdj-r2-t2-ionion .................................***Failed    0.04 sec
 953/2195 Test #1629: deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers_sdj-r2-t2-localecp ...............................***Failed    0.03 sec
 954/2195 Test #1630: deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers_sdj-r2-t2-nonlocalecp ............................***Failed    0.03 sec
 955/2195 Test #1631: deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers_sdj-r2-t2-flux ...................................***Failed    0.03 sec
 956/2195 Test #1632: deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers_sdj-r2-t2-s1-kinetic .............................***Failed    0.03 sec
 957/2195 Test #1633: deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers_sdj-r2-t2-s1-totenergy ...........................***Failed    0.03 sec
 958/2195 Test #1634: deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers_sdj-r2-t2-s1-eeenergy ............................***Failed    0.04 sec
 959/2195 Test #1635: deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers_sdj-r2-t2-s1-samples .............................***Failed    0.04 sec
 960/2195 Test #1636: deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers_sdj-r2-t2-s1-potential ...........................***Failed    0.04 sec
 961/2195 Test #1637: deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers_sdj-r2-t2-s1-ionion ..............................***Failed    0.03 sec
```

**To Reproduce**
1. Latest develop version
2. 
```
cmake -GNinja -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpiCC -DQMC_MIXED_PRECISION=1 -DCMAKE_BUILD_TYPE=Debug -DQMC_DATA=/scratch/pk7/QMC_DATA_FULL -DQMC_PERFORMANCE_NIO_MAX_ATOMS=128 -DQMC_PERFORMANCE_C_MOLECULE_MAX_ATOMS=12 -DQMC_PERFORMANCE_C_GRAPHITE_MAX_ATOMS=16 -DMPIEXEC_PREFLAGS="--bind-to;none;--oversubscribe" ../qmcpack
ninja
nohup ctest -j 48 -E long- --output-on-failure >& ctest.out &
```
with gcc 14.2.0, 12.40, OpenMPI 5.0.6, OpenBLAS 0.3.29 (current nightly test configs)

**Expected behavior**

All ctest tests should pass. 

**System:**
 nitrogen2, sulfur

**Additional context**
Interesting this got through CI. Found while doing manual checks of the Nexus update PRs.

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
reported by @correaa https://gitlab.com/correaa/boost-mpi3/-/jobs/11761762675
The libstdc++ in gcc15 included more assertions.
`Operator[]` of `std::vector` hit assertion failure **when size is zero**.
`Assertion '__n < this->size()' failed.`

We had a few `&vec[0]` and it can be changed to `vec.data()` or protected by `if(vec.size()>0)`
I fixed all the hits by deterministic tests.

Also fixes #5630

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
* * [x] I have read the pull request guidance and develop docs
* * [x] This PR is up to date with the current state of 'develop'
* * [x] Code added or changed in the PR has been clang-formatted
* * [ ] This PR adds tests to cover any new code, or to catch a bug that is being fixed
* * [ ] Documentation has been added (if appropriate)

### CODE REVIEW

File: src/QMCWaveFunctions/BsplineFactory/EinsplineSetBuilderCommon.cpp [hunk 1]
```diff
@@ -174,9 +174,12 @@ void EinsplineSetBuilder::BroadcastOrbitalInfo()
   if (primcell_kpoints.size() != NumTwists)
     primcell_kpoints.resize(NumTwists);
   bbuffer.add(&primcell_kpoints[0][0], &primcell_kpoints[0][0] + OHMMS_DIM * NumTwists);
-  bibuffer.add(&(TargetPtcl.DensityReducedGvecs[0][0]),
-               &(TargetPtcl.DensityReducedGvecs[0][0]) + numDensityGvecs * OHMMS_DIM);
-  bbuffer.add(&(TargetPtcl.Density_G[0]), &(TargetPtcl.Density_G[0]) + numDensityGvecs);
+  if (numDensityGvecs > 0)
+  {
+    bibuffer.add(&(TargetPtcl.DensityReducedGvecs[0][0]),
```
Comment (PDoakORNL) [inline src/QMCWaveFunctions/BsplineFactory/EinsplineSetBuilderCommon.cpp:183]: It's not clear what is going on here, in a month I won't know this has anything to do with the assert on operator[] and when reading it have to go search for weather numDensityGvecs is releated to the size of this object or not again. Define numDensityGvecs right here before use or just make the actual  `TargetPtcl.DensityReducedGvecs.empty()` code should maximize clarity for the reader.

**Review by PDoakORNL — CHANGES_REQUESTED** [review]
This LGTM with the exception of what is going on with EinsplineSetBuilderCommon.cpp

File: src/QMCWaveFunctions/BsplineFactory/EinsplineSetBuilderCommon.cpp (hunk 1 above)
Comment (ye-luo) [reply src/QMCWaveFunctions/BsplineFactory/EinsplineSetBuilderCommon.cpp:183]: `numDensityGvecs` is the communicated size, namely source of truth for both `DensityReducedGvecs` and `Density_G`. it is better than testing the size of either array. I just added a few asserts.

Comment (PDoakORNL) [reply src/QMCWaveFunctions/BsplineFactory/EinsplineSetBuilderCommon.cpp:183]: It's clear enough for me now.

**Review by PDoakORNL — APPROVED** [review]
LGTM
