### PR TITLE
Fix gcc7 builds

### LINKED ISSUE #3400: Compilation failure with GCC 7.5.0
**Describe the bug**
QMCPACK fails to build when GCC 7.5.0 is used (released Nov. 14, 2019).  The issue relates to private access:

```
[ 20%] Building CXX object src/QMCWaveFunctions/CMakeFiles/qmcwfs.dir/BsplineFactory/createComplexDouble.cpp.o
In file included from /home/j1k/projects/ecp/16_batched_nofk/qmcpack_batched_nofk/src/QMCWaveFunctions/BsplineFactory/createComplexDouble.cpp:30:0:
/home/j1k/projects/ecp/16_batched_nofk/qmcpack_batched_nofk/src/QMCWaveFunctions/BsplineFactory/HybridRepSetReader.h: In instantiation of ‘void qmcplusplus::HybridRepSetReader<SA>::initialize_hybridrep_atomic_centers() [with SA = qmcplusplus::HybridRepCplx<qmcplusplus::SplineC2R<double> >]’:
/home/j1k/projects/ecp/16_batched_nofk/qmcpack_batched_nofk/src/QMCWaveFunctions/BsplineFactory/createComplexDouble.cpp:103:1:   required from here
/home/j1k/projects/ecp/16_batched_nofk/qmcpack_batched_nofk/src/QMCWaveFunctions/BsplineFactory/HybridRepSetReader.h:165:16: error: ‘qmcplusplus::HybridRepCenterOrbitals<double>::smoothing_schemes qmcplusplus::HybridRepCenterOrbitals<double>::smooth_scheme’ is private within this context
       bspline->smooth_scheme = SA::smoothing_schemes::CONSISTENT;
       ~~~~~~~~~^~~~~~~~~~~~~
```

**To Reproduce**
1. release version or git commit hash being built

```
commit 6161091baa344f06eb618ed7c859a287427a7630 (HEAD -> develop, main/develop)
Merge: 9818a4703 897da66e1
Author: Ye Luo <yeluo@anl.gov>
Date:   Mon Aug 30 09:32:46 2021 -0500

    Merge pull request #3257 from shivupa/spinonebody
    
    One Body Spin dependent Jastrow
```

2. cmake command

On Ubuntu 18.04.5 LTS:

```
export CXX=mpiCC

echo "building soa real"
mkdir build_soa_real
cd build_soa_real
cmake -DENABLE_SOA=1 ..
make -j 24
cd ..
ln -s ./build_soa_real/bin/qmcpack qmcpack_soa_real
```

**Expected behavior**
Clean build.

**System:**
 - system name: Ubuntu laptop

### PR DESCRIPTION
**Pull request by prckent**
## Proposed changes

Closes #3400 . Workaround gcc7 build problem. Since not present with other compilers, presumed a since fixed compiler bug.

## What type(s) of changes does this code introduce?

- Bugfix

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

sulfur, nompi, gcc7.5. Build & full deterministic set.

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- NA. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- NA. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Start testing in-house

**Review by ye-luo — APPROVED** [review]

File: src/QMCWaveFunctions/BsplineFactory/HybridRepCenterOrbitals.h [hunk 1]
```diff
@@ -406,7 +406,11 @@ class HybridRepCenterOrbitals
   using RealType     = typename DistanceTableData::RealType;
   using PosType      = typename DistanceTableData::PosType;
 
+#if (defined(__GNUC__) && (__GNUC__== 7))
+// Workaround GCC 7.5 and presumed earlier bug. Leave member data public.
```
Comment (markdewing) [inline src/QMCWaveFunctions/BsplineFactory/HybridRepCenterOrbitals.h:410]: Might be helpful to put the bug report number here.
