### PR TITLE
Require high precision sqrt in mixed precision builds with Intel compiler

### LINKED ISSUE #2569: deterministic-unit_test_wavefunction fails in mixed precision
**Describe the bug**

https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=deterministic-unit_test_wavefunction&date=2020-07-02

It appears that at least the tolerances for two of the tests need to be increased in mixed precision, inside the source.

```
[0mHybridrep SPO from HDF diamond_2x1x1
 [0m-------------------------------------------------------------------------------
 [0;37m/scratch/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/qmcpack-develop/src/QMCWaveFunctions/tests/test_hybridrep.cpp:152
 [0m...............................................................................

 [0;37m/scratch/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/qmcpack-develop/src/QMCWaveFunctions/tests/test_hybridrep.cpp:261:  [0m [1;31mFAILED:
 [0m [0;36m  REQUIRE( std::real(d2psiM[0][1]) == Approx(-0.7860302329).epsilon(1e-4) )
 [0mwith expansion:
 [1;33m  -0.78655f == Approx( -0.7860302329 )
 [0m
```

and

```
TrialWaveFunction_diamondC_2x1x1
-------------------------------------------------------------------------------
/scratch/pk7/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/qmcpack/src/QMCWaveFunctions/tests/test_TrialWaveFunction_diamondC_2x1x1.cpp:442
...............................................................................

/scratch/pk7/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/qmcpack/src/QMCWaveFunctions/tests/test_TrialWaveFunction_diamondC_2x1x1.cpp:374: FAILED:
  REQUIRE( grad_old[0][0] == ComplexApprox(ValueType(-114.82740072726, -7.605305979232e-05)).epsilon(8e-5) )
with expansion:
  (-114.842,0.00138425)
  ==
  ComplexApprox( (-114.827,-7.60531e-05) )
```

Note that with clang10 on nitrogen, the tests do pass https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=deterministic-unit_test_wavefunction&date=2020-07-01

**To Reproduce**

Latest develop, mixed precision builds. Run ctest -R  deterministic-unit_test_wavefunction

**Expected behavior**

Test passes

**System:**

bora, sulfur...

**Additional context**

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes

Fixes #2569 
Intel compiler by default pickup low precision sqrt and caused problems in mixed precision build.
Adds a r^2 == dr^2 check requiring exact matching.

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
Bora(Clang, Intel, GNU), Summit(XL)

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

File: src/QMCWaveFunctions/tests/test_hybridrep.cpp [hunk 1]
```diff
@@ -238,6 +238,13 @@ TEST_CASE("Hybridrep SPO from HDF diamond_2x1x1", "[wavefunction]")
   ions_.update();
   elec_.update();
 
+  ParticleSet::RealType r;
+  ParticleSet::PosType dr;
+  elec_.getDistTable(0).get_first_neighbor(0, r, dr, false);
+  std::cout << std::setprecision(14) << "check r^2 against dr^2. "
+            << "r= " << r << " dr = " << dr << std::endl;
+  REQUIRE(r * r == dot(dr, dr));
```
Comment (prckent) [inline src/QMCWaveFunctions/tests/test_hybridrep.cpp:246]: Realistically I think a couple of machine epsilon of tolerance is needed here.

Comment (ye-luo) [reply src/QMCWaveFunctions/tests/test_hybridrep.cpp:246]: Even before the change `std::numeric_limits<ParticleSet::RealType>::epsilon()` passes.
Are you comfortable with `std::numeric_limits<double>::epsilon()`?

**Comment by prckent** [comment]
Was the behavior changed after v2018? A quick search did not find any indication.

**Comment by ye-luo** [comment]
> Was the behavior changed after v2018? A quick search did not find any indication.

No change of behaviour. 2018, 2019, 2020(2019.1) all have the same behaviour.

File: src/QMCWaveFunctions/tests/test_hybridrep.cpp (hunk 1 above)
Comment (prckent) [reply src/QMCWaveFunctions/tests/test_hybridrep.cpp:246]: Yes. Not a big deal. I am surprised we haven't run into this problem with other compilers/optimized math implementations, since taking shortcuts in sqrt is a common optimization.
