### PR TITLE
One Body Spin dependent Jastrow

### LINKED ISSUE #3138: Spin dependent One body Jastrow factor is needed
**Describe the bug**
When running a calculation with >2 particle types, only the last one body Jastrow factor is optimized. The rest have no values. This seems to be related to https://github.com/QMCPACK/qmcpack/pull/3052

Potential Solution?:
I haven't looked further into this issue yet. It seems similar to the two body issue

**To Reproduce**
1. b1a4692e86ef7b2a55242f3ba845d7eb88191ad9-dirty
2. cmake command : `cmake -DCMAKE_BUILD_TYPE=Debug ..`
3. `qmcpack Li_wpos.qmc.in-wfj.xml`
The files needed to replicate this issue are located here https://gist.github.com/shivupa/9bfc976b35efbfe9b84a64a568197603.

**Expected behavior**
One body jastrow parameters could be optimized.

**System:**
 - Workstation Intel i7-2600S

**Additional context**
During the optimization the parameters do not appear in the optvariables
```
  <optVariables href="Li_wpos.s005.opt.xml">
 uu_0                -3.865297e-02 1 1  ON 0
 uu_1                -3.432272e-01 1 1  ON 1
 ud_0                -6.051654e-02 1 1  ON 2
 ud_1                 1.829733e-01 1 1  ON 3
 up_0                -4.290780e-01 1 1  ON 4
 up_1                -4.227348e-01 1 1  ON 5
 dd_0                -1.125009e-01 1 1  ON 6
 dd_1                -3.337817e-01 1 1  ON 7
 dp_0                -4.457856e-01 1 1  ON 8
 dp_1                -3.864281e-01 1 1  ON 9
pLi_0                -1.002001e-01 1 1  ON 10
pLi_1                 4.909281e-01 1 1  ON 11
  </optVariables>
```
but at the start of the output the variables are printed
```
   Jastrow
   -------
    Name: J2   Type: Two-Body   Function: Bspline

    Radial function for species: u - u
     Number of parameters: 2
     Cusp: -0.25
     Cutoff radius: 10

     Name                        Value Type Recompute Use Index
     ---- ---------------------------- ---- --------- --- -----
     uu_0                -4.394752e-02    1         1  ON     0
     uu_1                -2.293588e-01    1         1  ON     1

    Radial function for species: d - d
     Number of parameters: 2
     Cusp: -0.25
     Cutoff radius: 10

     Name                        Value Type Recompute Use Index
     ---- ---------------------------- ---- --------- --- -----
     dd_0                -5.433334e-02    1         1  ON     0
     dd_1                -1.663821e-01    1         1  ON     1

    Radial function for species: u - d
     Number of parameters: 2
     Cusp: -0.5
     Cutoff radius: 10

     Name                        Value Type Recompute Use Index
     ---- ---------------------------- ---- --------- --- -----
     ud_0                 3.818599e-01    1         1  ON     0
     ud_1                 2.278448e-01    1         1  ON     1

    Radial function for species: u - p
     Number of parameters: 2
     Cusp: 0.5
     Cutoff radius: 10

     Name                        Value Type Recompute Use Index
     ---- ---------------------------- ---- --------- --- -----
     up_0                -9.478729e-01    1         1  ON     0
     up_1                -6.388483e-01    1         1  ON     1

    Radial function for species: d - p
     Number of parameters: 2
     Cusp: 0.5
     Cutoff radius: 10

     Name                        Value Type Recompute Use Index
     ---- ---------------------------- ---- --------- --- -----
     dp_0                -1.008447e+00    1         1  ON     0
     dp_1                -6.491591e-01    1         1  ON     1


   Jastrow
   -------
    Name: J1   Type: One-Body   Function: Bspline

    Radial function for element: Li
     Number of parameters: 2
     Cusp: 0
     Cutoff radius: 10

      Name                        Value Type Recompute Use Index
     ----- ---------------------------- ---- --------- --- -----
     uLi_0                -7.571247e-01    1         1  ON     0
     uLi_1                -5.042248e-01    1         1  ON     1

    Radial function for element: Li
     Number of parameters: 2
     Cusp: 0
     Cutoff radius: 10

      Name                        Value Type Recompute Use Index
     ----- ---------------------------- ---- --------- --- -----
     dLi_0                -7.571247e-01    1         1  ON     0
     dLi_1                -5.042248e-01    1         1  ON     1

    Radial function for element: Li
     Number of parameters: 2
     Cusp: 0
     Cutoff radius: 10

      Name                        Value Type Recompute Use Index
     ----- ---------------------------- ---- --------- --- -----
     pLi_0                -7.571247e-01    1         1  ON     0
     pLi_1                -5.042248e-01    1         1  ON     1
```

### PR DESCRIPTION
**Pull request by shivupa**
## Proposed changes
This adds (re-adds) spin dependent one-body Jastrow factors. This builds upon #3243 #3256 (This will need to be rebased after those go in so no need to look at until those are addressed.).
Closes #3138.
## What type(s) of changes does this code introduce?
- New(?) feature
- Testing changes (e.g. new unit/integration/performance tests)
### Does this introduce a breaking change?
- No
## What systems has this change been tested on?
Ryzen Workstation
## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by shivupa** [comment]
A test that I still want to add is a short run with the regular 1 body Jastrow and a 1 body Jastrow with separate up and down channels with the same parameters and make sure they agree. I am not sure how to write a test like that yet, but I will try to add something shortly.

File: src/QMCWaveFunctions/Jastrow/RadialJastrowBuilder.cpp [hunk 1]
```diff
@@ -513,12 +599,26 @@ std::unique_ptr<WaveFunctionComponent> RadialJastrowBuilder::buildComponent(xmlN
     // it's a one body jastrow factor
     if (Jastfunction == "bspline")
     {
-      return createJ1<BsplineFunctor<RealType>>(cur);
+      if (SpinOpt.find("yes") < SpinOpt.size())
```
Comment (markdewing) [inline src/QMCWaveFunctions/Jastrow/RadialJastrowBuilder.cpp:602]: This would be more straightforward as `if (SpinOpt == "yes")`
(Unless I'm missing something about the values of SpinOpt - it is just "yes" or "no"?)

Comment (shivupa) [reply src/QMCWaveFunctions/Jastrow/RadialJastrowBuilder.cpp:602]: Thanks I agree it will be just yes or no. I will update this accordingly

Comment (ye-luo) [reply src/QMCWaveFunctions/Jastrow/RadialJastrowBuilder.cpp]: https://github.com/QMCPACK/qmcpack/blob/9dfd387e343ed0ecab8583a7de4c26baba225794/src/io/OhmmsData/AttributeSet.h#L58
Use the third argument to restrict input options.

Comment (shivupa) [reply src/QMCWaveFunctions/Jastrow/RadialJastrowBuilder.cpp]: updated. Thanks didn't know about that

Comment (ye-luo) [reply src/QMCWaveFunctions/Jastrow/RadialJastrowBuilder.cpp]: I think the default should be no. So `{"no", "yes"}`. Don't do the change now. I'm putting up a lot of review comments. I think we we should take the chance to do our best as the old one is intended to be deleted.

File: src/QMCWaveFunctions/Jastrow/J1Spin.h [hunk 2]
```diff
@@ -0,0 +1,854 @@
...
+  using valT = typename FT::real_type;
+  ///element position type
+  using posT = TinyVector<valT, OHMMS_DIM>;
+  ///use the same container
+  using DistRow  = DistanceTableData::DistRow;
+  using DisplRow = DistanceTableData::DisplRow;
+  ///table index
+  const int myTableID;
+  ///number of ions
+  int Nions;
```
Comment (ye-luo) [inline src/QMCWaveFunctions/Jastrow/J1Spin.h:48]: This needs to be const and set at the constructor.

File: src/QMCWaveFunctions/Jastrow/J1Spin.h [hunk 3]
```diff
@@ -0,0 +1,854 @@
...
+  /* the number of ion groups if ions in 'Ions' particleset are grouped by species. 0 otherwise.
+   * 0 Use slow code path. >= 1 use the code path with ion grouping
+   */
+  const int NumGroups;
+  // number of electron groups
+  const int NumTargetGroups;
+  ///reference to the sources (ions)
+  const ParticleSet& Ions;
+  ///reference to the target (elecs)
+  const ParticleSet& Elecs;
```
Comment (ye-luo) [inline src/QMCWaveFunctions/Jastrow/J1Spin.h:60]: Keeping a reference of Elecs is ricky. Jastrow object should be tided to a  particular electron ParticleSet object.

File: src/QMCWaveFunctions/Jastrow/J1Spin.h [hunk 4]
```diff
@@ -0,0 +1,854 @@
...
+  Vector<valT> Vat;
+  aligned_vector<valT> U, dU, d2U, d3U;
+  aligned_vector<valT> DistCompressed;
+  aligned_vector<int> DistIndice;
+  Vector<posT> Grad;
+  Vector<valT> Lap;
+  ///Container for \f$F[ig*NIons+jg]\f$
+  std::vector<FT*> J1Functors;
+  ///container for the unique Jastrow functions
+  std::map<std::string, std::unique_ptr<FT>> J1UniqueFunctors;
```
Comment (ye-luo) [inline src/QMCWaveFunctions/Jastrow/J1Spin.h:81]: J1Functors if size Nelec x Nionis big and thus bad.
J1UniqueFunctors can be just NTargetGroups x NSourceGroups.

File: src/QMCWaveFunctions/Jastrow/J1Spin.h [hunk 5]
```diff
@@ -0,0 +1,854 @@
...
+
+  std::vector<std::pair<int, int>> OffSet;
+  Vector<RealType> dLogPsi;
+  typedef ParticleAttrib<QTFull::GradType> WavefunctionFirstDerivativeType;
+  typedef ParticleAttrib<QTFull::ValueType> WavefunctionSecondDerivativeType;
+  std::vector<WavefunctionFirstDerivativeType*> gradLogPsi;
```
Comment (ye-luo) [inline src/QMCWaveFunctions/Jastrow/J1Spin.h:87]: pointer is bad. why not just remove the pointer and use the container directly? Resize should be done when WF optimization is used.

File: src/QMCWaveFunctions/Jastrow/J1Spin.h [hunk 6]
```diff
@@ -0,0 +1,854 @@
...
+    if (myName.empty())
+      throw std::runtime_error("J1Spin object name cannot be empty!");
+    initialize();
+  }
+
+  J1Spin(const J1Spin& rhs) = delete;
+
+  ~J1Spin() override
+  {
+    delete_iter(gradLogPsi.begin(), gradLogPsi.end());
```
Comment (ye-luo) [inline src/QMCWaveFunctions/Jastrow/J1Spin.h:110]: If not using pointers,  these delete go away.

File: src/QMCWaveFunctions/Jastrow/J1Spin.h [hunk 7]
```diff
@@ -0,0 +1,854 @@
...
+
+  void addFunc(int source_type, std::unique_ptr<FT> afunc, int target_type = -1)
+  {
+    // if target type is not specified J1Functors[i,:] is assigned
+    // if target type is specified J1Functors[i,j] is assigned
+    //
+    // if target type is not specified J1UniqueFunctors["i"] is assigned
+    // if target type is specified J1UniqueFunctors["ij"] is assigned
+    //
+    app_log() << " source" << source_type << " target type " << target_type << std::endl;
```
Comment (ye-luo) [inline src/QMCWaveFunctions/Jastrow/J1Spin.h:150]: If the electron species is not give, we can populate every target species with clones of the same unique_ptr.
I hope we only need J1UniqueFunctors and never need J1Functors.
I think `Unique` is with respect to particle groups. Spin symmetry generally should be handled in the builder not inside this function.

For example, if you have spin-up, down electrons and positrons, you would like to populate up/down electron with the same Jastrow but positrons with a different one, I don't see the symmetry can be well recorded in J1UniqueFunctors.
For this reason, my assessment on J1UniqueFunctors is that it is to represent groups.

Inside unique J1 functor, it should carry shared_ptr for optimization info. The symmetry can be linked there and builder should handle this.

File: src/QMCWaveFunctions/Jastrow/J1Spin.h [hunk 8]
```diff
@@ -0,0 +1,854 @@
...
+    }
+  }
+
+
+  inline valT computeU(const ParticleSet& P, int iat, const DistRow& dist)
+  {
+    valT curVat(0);
+    if (NumGroups > 0)
+    {
+      std::stringstream aname;
```
Comment (ye-luo) [inline src/QMCWaveFunctions/Jastrow/J1Spin.h:363]: ugly piece from map.

File: src/QMCWaveFunctions/Jastrow/J1Spin.h [hunk 9]
```diff
@@ -0,0 +1,854 @@
...
+    {
+      gradLogPsi[i] = new WavefunctionFirstDerivativeType(Nelec);
+      lapLogPsi[i]  = new WavefunctionSecondDerivativeType(Nelec);
+    }
+  }
+
+
+  std::unique_ptr<WaveFunctionComponent> makeClone(ParticleSet& tqp) const override
+  {
+    auto j1copy         = std::make_unique<J1Spin<FT>>(myName, Ions, tqp);
```
Comment (ye-luo) [inline src/QMCWaveFunctions/Jastrow/J1Spin.h:625]: please move all the contents of makeClone into a copy constructor and makeClone should just invoke the copy constructor.

File: src/QMCWaveFunctions/Jastrow/J1Spin.h [hunk 10]
```diff
@@ -0,0 +1,854 @@
...
+      gid << source.getGroupID(isrc) << P.getGroupID(iat);
+      if (J1UniqueFunctors.find(gid.str()) == J1UniqueFunctors.end())
+      {
+        gid.str() = "";
+        gid << source.getGroupID(isrc);
+      }
+
+      if (J1UniqueFunctors[gid.str()] != nullptr)
+      {
+        U[isrc] = J1UniqueFunctors[gid.str()]->evaluate(dist[isrc], dU[isrc], d2U[isrc], d3U[isrc]);
```
Comment (ye-luo) [inline src/QMCWaveFunctions/Jastrow/J1Spin.h:825]: remove {} around 1 line.

File: src/QMCWaveFunctions/Jastrow/J1Spin.h [hunk 11]
```diff
@@ -0,0 +1,854 @@
...
+      }
+      else
+      {
+        APP_ABORT("J1OrbitalSoa::evaluateGradSource:  J1UniqueFunctors[gid]==nullptr")
```
Comment (ye-luo) [inline src/QMCWaveFunctions/Jastrow/J1Spin.h:829]: throw runtime_error

**Review by ye-luo — CHANGES_REQUESTED** [review]
My first round of comment.

File: src/QMCWaveFunctions/Jastrow/J1Spin.h (hunk 7 above)
Comment (shivupa) [reply src/QMCWaveFunctions/Jastrow/J1Spin.h:150]: > I hope we only need J1UniqueFunctors and never need J1Functors. 
I think this might be possible. I need more time

File: src/QMCWaveFunctions/Jastrow/J1Spin.h (hunk 2 above)
Comment (shivupa) [reply src/QMCWaveFunctions/Jastrow/J1Spin.h]: Fixed

File: src/QMCWaveFunctions/Jastrow/J1Spin.h (hunk 3 above)
Comment (shivupa) [reply src/QMCWaveFunctions/Jastrow/J1Spin.h]: Removed

File: src/QMCWaveFunctions/Jastrow/J1Spin.h (hunk 4 above)
Comment (shivupa) [reply src/QMCWaveFunctions/Jastrow/J1Spin.h]: Only `J1UniqueFunctors` exists now

File: src/QMCWaveFunctions/Jastrow/J1Spin.h (hunk 5 above)
Comment (shivupa) [reply src/QMCWaveFunctions/Jastrow/J1Spin.h]: Done

File: src/QMCWaveFunctions/Jastrow/J1Spin.h (hunk 9 above)
Comment (shivupa) [reply src/QMCWaveFunctions/Jastrow/J1Spin.h]: Done

File: src/QMCWaveFunctions/Jastrow/J1Spin.h (hunk 7 above)
Comment (shivupa) [reply src/QMCWaveFunctions/Jastrow/J1Spin.h]: > Inside unique J1 functor, it should carry shared_ptr for optimization info. The symmetry can be linked there and builder should handle this.

Let me know if the current iteration of this is similar to what you are expecting.

**Comment by ye-luo** [comment]
Old files with J1SpinOrbitalSoA in the name reappear. Could you just squash all the commits? The current commits are not clean and will be difficult to continue being rebased.

**Comment by shivupa** [comment]
Yeah oops sorry about that. The rebase was getting complicated

**Comment by ye-luo** [comment]
Start testing in-house

**Review by ye-luo — DISMISSED** [review]

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]
