### PR TITLE
Fix cuda testing

### LINKED ISSUE #2390: Large breakage in CUDA code and deterministic tests
**Describe the bug**

100+ deterministic tests are failing for cuda complex, real, and full precision builds.

Deviations from expected values are sizable. e.g. 2 million sigma for diamond 2x1x1 https://cdash.qmcpack.org/CDash/testDetails.php?test=7938301&build=112564

Yesterday's https://github.com/QMCPACK/qmcpack/pull/2382 was checked, so most likely another PR caused a problem.

**To Reproduce**
1. release version or git commit hash being built
2. cmake command
3. full program/test invocation command
4. additional steps

Run the deterministic tests from the latest develop for any CUDA version.

**Expected behavior**

Tests should pass

**System:**
 - system name [e.g. fusiont5, summit]
 - modules loaded [e.g. output of `module list`]
 - other systems where this is reproducible [e.g. "my laptop", "none"]

nitrogen, standard nightly build configuration.

**Additional context**

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
closes #2390
Skip spin initialization in CUDA builds to restore deterministic tests.
Now if SpinMoves is requested, legacy CUDA aborts.

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
bora

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by prckent** [comment]
Confirming that the CUDA deterministic tests are largely working after this fix.

**Comment by ye-luo** [comment]
> Restore
> 
> ```
>   tolower(SpinMoves);
>   if (SpinMoves != "yes" && SpinMoves != "no") 
>   {
>     APP_ABORT("SpinMoves must be yes/no\n");
>   }
> ```

This is  moved to one level up in QMCDriver.cpp

File: src/QMCDrivers/QMCDriver.cpp [hunk 1]
```diff
@@ -517,14 +521,15 @@ bool QMCDriver::putQMCInfo(xmlNodePtr cur)
   if (!AppendRun)
     CurrentStep = 0;
 
- 
-
- 
+  tolower(SpinMoves);
+  if (SpinMoves != "yes" && SpinMoves != "no")
+    myComm->barrier_and_abort("SpinMoves must be yes/no!\n");
```
Comment (ye-luo) [inline src/QMCDrivers/QMCDriver.cpp:526]: "SpinMoves must be yes/no!\n" error trap is here
